/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hydroponicgarden1;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import org.netbeans.lib.awtextra.AbsoluteLayout;
/**
 *
 * @author Kazuto
 */
public class Inicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    /**
     * Creates new form Inicio
     */
    
    private boolean menuAbierto = false;
    private final int anchoMenu = 180;
    
    public Inicio() {
        initComponents();
        // Establece el color de fondo de la ventana.
        getContentPane().setBackground(new Color(233, 225, 225));
        
        // Coloca el menú oculto al iniciar la aplicación.
        panelMenu.setLocation(-anchoMenu,55);
        // Configura las acciones de cada botón del menú.
        configurarMenu();
        // Cargar el logotipo principal del sistema.
        try {

            // Cargar la imagen principal del logo
            ImageIcon icono = new ImageIcon(getClass().getResource("/imagen/hydrofarm_logo.png"));

            Image imagen = icono.getImage().getScaledInstance(
                80, 80,
                Image.SCALE_SMOOTH
            );

            LabelIcon.setIcon(new ImageIcon(imagen));
        } catch (Exception e) {
            System.err.println("Error 1: " + e.getMessage());
        }
        // Cargar la imagen principal de la pantalla de inicio.
        ImageIcon icono = new ImageIcon(getClass().getResource("/imagen/home.png"));
        LableImageHome.setIcon(icono);
        // Actualizar y mostrar correctamente la interfaz.
        this.revalidate();
        this.repaint();
        this.setVisible(true);
        
    }
//Abre y cierra el menú lateral mediante una animación utilizando un Timer.
    private void animarMenu() {
        // Crear el temporizador que controlará la animación.
        Timer timer = new Timer(5, null);
        
        timer.addActionListener(e -> {
            // Verificar si el menú está cerrado para abrirlo.
            if (!menuAbierto) {

                // Desplazar el menú hacia la derecha.
                if (panelMenu.getX() < 0) {

                    panelMenu.setLocation(
                            panelMenu.getX() + 10,
                            55);

                } else {
                    // Finalizar la apertura del menú.
                    panelMenu.setLocation(0,55);
                    menuAbierto = true;
                    timer.stop();
                }

            } else {

                // Desplazar el menú hacia la izquierda para cerrarlo.
                if (panelMenu.getX() > -anchoMenu) {

                    panelMenu.setLocation(
                            panelMenu.getX() - 10,
                            55);

                } else {
                    // Finalizar el cierre del menú.
                    panelMenu.setLocation(-anchoMenu,55);
                    menuAbierto = false;
                    timer.stop();
                }
            }
        });
        // Iniciar la animación.
        timer.start();
    }
//Configura las acciones de navegación de todos los botones del menú lateral.
    private void configurarMenu() {
    // Mantener la ventana actual y cerrar el menú si está abierto.
    homeBtn1.addActionListener(e -> {
        if (menuAbierto) animarMenu();
    });
    // Abrir la ventana de Sistemas de Huerto.
    systemBtn1.addActionListener(e -> {
        new VentanaPrincipal().setVisible(true);
        dispose();
    });
    // Abrir la ventana de Planta
    plantBtn1.addActionListener(e -> {
        new planta().setVisible(true);
        dispose();
    });
    // Abrir la ventana de Lote
    loteBtn1.addActionListener(e -> {
        new GestionLotes().setVisible(true);
        dispose();
    });
    // Abrir la ventana de monitoreo
    monitoreoBtn1.addActionListener(e -> {
        new InterfazChida().setVisible(true);
        dispose();
    });
    // Abrir la ventana de Solucion
    solutionBtn1.addActionListener(e -> {
        new SolucionNutritivaPanel().setVisible(true);
        dispose();
    });
    // Abrir la ventana de perfil
    perfilBtn1.addActionListener(e -> {
        new Profile().setVisible(true);
        dispose();
    });
    // Cerrar el programa y regresar al login
    CloseBtn1.addActionListener(e -> {
        new Login().setVisible(true);
        dispose();
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        LabelIcon = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        LableImageHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        homeBtn1 = new javax.swing.JButton();
        systemBtn1 = new javax.swing.JButton();
        plantBtn1 = new javax.swing.JButton();
        loteBtn1 = new javax.swing.JButton();
        monitoreoBtn1 = new javax.swing.JButton();
        solutionBtn1 = new javax.swing.JButton();
        perfilBtn1 = new javax.swing.JButton();
        CloseBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principalPanel.setBackground(new java.awt.Color(233, 225, 225));
        principalPanel.setPreferredSize(new java.awt.Dimension(791, 548));

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));

        LabelTitle.setBackground(new java.awt.Color(0, 204, 0));
        LabelTitle.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 30)); // NOI18N
        LabelTitle.setForeground(new java.awt.Color(0, 153, 0));
        LabelTitle.setText("HydroFarm   ");

        btnMenu.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnMenu.setText("☰");
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu)
                .addGap(137, 137, 137)
                .addComponent(LabelIcon)
                .addGap(290, 290, 290)
                .addComponent(LabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelIcon)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMenu)
                        .addComponent(LabelTitle)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setPreferredSize(new java.awt.Dimension(791, 548));

        LableImageHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/home.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenidos a HydroFarm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sistema de gestión y monitoreo para huertos hidropónicos.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("y mucho más");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Desde aquí podrás administrar tus cultivos, monitorear sensores, consultar reportes");

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LableImageHome)
                            .addGroup(contentPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2))))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(LableImageHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        panelMenu.setBackground(new java.awt.Color(0, 153, 0));
        panelMenu.setPreferredSize(new java.awt.Dimension(180, 305));

        homeBtn1.setBackground(new java.awt.Color(66, 127, 53));
        homeBtn1.setForeground(new java.awt.Color(255, 255, 255));
        homeBtn1.setText("Inicio");
        homeBtn1.setBorderPainted(false);
        homeBtn1.setFocusPainted(false);

        systemBtn1.setBackground(new java.awt.Color(66, 127, 53));
        systemBtn1.setForeground(new java.awt.Color(255, 255, 255));
        systemBtn1.setText("Sistema Huerto");
        systemBtn1.setBorderPainted(false);
        systemBtn1.setContentAreaFilled(false);
        systemBtn1.setFocusPainted(false);

        plantBtn1.setForeground(new java.awt.Color(255, 255, 255));
        plantBtn1.setText("Plantas");
        plantBtn1.setBorderPainted(false);
        plantBtn1.setContentAreaFilled(false);
        plantBtn1.setFocusPainted(false);
        plantBtn1.addActionListener(this::plantBtn1ActionPerformed);

        loteBtn1.setForeground(new java.awt.Color(255, 255, 255));
        loteBtn1.setText("Lotes");
        loteBtn1.setBorderPainted(false);
        loteBtn1.setContentAreaFilled(false);
        loteBtn1.setFocusPainted(false);

        monitoreoBtn1.setForeground(new java.awt.Color(255, 255, 255));
        monitoreoBtn1.setText("Monitoreo");
        monitoreoBtn1.setBorderPainted(false);
        monitoreoBtn1.setContentAreaFilled(false);
        monitoreoBtn1.setFocusPainted(false);

        solutionBtn1.setForeground(new java.awt.Color(255, 255, 255));
        solutionBtn1.setText("Solución Nutritiva");
        solutionBtn1.setBorderPainted(false);
        solutionBtn1.setContentAreaFilled(false);
        solutionBtn1.setFocusPainted(false);
        solutionBtn1.addActionListener(this::solutionBtn1ActionPerformed);

        perfilBtn1.setForeground(new java.awt.Color(255, 255, 255));
        perfilBtn1.setText("Mi Perfil");
        perfilBtn1.setBorderPainted(false);
        perfilBtn1.setContentAreaFilled(false);
        perfilBtn1.setFocusPainted(false);
        perfilBtn1.addActionListener(this::perfilBtn1ActionPerformed);

        CloseBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CloseBtn1.setText("Cerrar Sesión");
        CloseBtn1.setBorderPainted(false);
        CloseBtn1.setContentAreaFilled(false);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(perfilBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(solutionBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monitoreoBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loteBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(systemBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(homeBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CloseBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systemBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plantBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loteBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monitoreoBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solutionBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(perfilBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseBtn1)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(principalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        // Ejecutar la animación del menú lateral.
        animarMenu();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void perfilBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilBtn1ActionPerformed
        // TODO add your handling code here:
        // Crear una nueva ventana del perfil.
        Profile perfil = new Profile();
        // Mostrar la ventana del perfil.
        perfil.setVisible(true);
        // Cerrar la ventana actual.
        dispose();
    }//GEN-LAST:event_perfilBtn1ActionPerformed

    private void plantBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantBtn1ActionPerformed

    private void solutionBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solutionBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn1;
    private javax.swing.JLabel LabelIcon;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JLabel LableImageHome;
    private javax.swing.JButton btnMenu;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton homeBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loteBtn1;
    private javax.swing.JButton monitoreoBtn1;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JButton perfilBtn1;
    private javax.swing.JButton plantBtn1;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JButton solutionBtn1;
    private javax.swing.JButton systemBtn1;
    // End of variables declaration//GEN-END:variables
}
