/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hydroponicgarden1;

import javax.swing.Timer;
import com.mycompany.hydroponicgarden1.model.User;
import com.mycompany.hydroponicgarden1.session.session;
import java.util.Calendar;
import javax.swing.JOptionPane;
import com.mycompany.hydroponicgarden1.dao.UserDAO;

/**
 *
 * @author Kazuto
 */
public class Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());

    /**
     * Creates new form Profile
     */
    private boolean menuAbierto = false;
    private final int anchoMenu = 180;
    
    public Profile() {
        initComponents();
        
        loadDateCombos();
        cargarDatosUsuario();
        configurarMenu();
        
        
    }
    
    private void animarMenu() {

        Timer timer = new Timer(5, null);

        timer.addActionListener(e -> {

            if (!menuAbierto) {

                // Abrir menú
                if (menuPanel.getX() < 0) {

                    menuPanel.setLocation(
                            menuPanel.getX() + 10,
                            55);

                } else {

                    menuPanel.setLocation(0,55);
                    menuAbierto = true;
                    timer.stop();
                }

            } else {

                // Cerrar menú
                if (menuPanel.getX() > -anchoMenu) {

                    menuPanel.setLocation(
                            menuPanel.getX() - 10,
                            55);

                } else {

                    menuPanel.setLocation(-anchoMenu,55);
                    menuAbierto = false;
                    timer.stop();
                }
            }
        });

        timer.start();
    }
    private void configurarMenu() {

    profileBtn.addActionListener(e -> {
        if (menuAbierto) animarMenu();
    });

    systemBtn.addActionListener(e -> {
        new VentanaPrincipal().setVisible(true);
        dispose();
    });

    plantBtn.addActionListener(e -> {
        new planta().setVisible(true);
        dispose();
    });

    loteBtn.addActionListener(e -> {
        new GestionLotes().setVisible(true);
        dispose();
    });

    monitoreoBtn.addActionListener(e -> {
        new InterfazChida().setVisible(true);
        dispose();
    });

    solutionBtn.addActionListener(e -> {
        new SolucionNutritivaPanel().setVisible(true);
        dispose();
    });

    homeBtn.addActionListener(e -> {
        new Inicio().setVisible(true);
        dispose();
    });

    logoutBtn.addActionListener(e -> {
        new Login().setVisible(true);
        dispose();
    });
}
    private void loadDateCombos() {

    cmbDay.removeAllItems();
    cmbMonth.removeAllItems();
    cmbYear.removeAllItems();

    // Days
    for (int i = 1; i <= 31; i++) {
        cmbDay.addItem(String.valueOf(i));
    }

    // Months
    for (int i = 1; i <= 12; i++) {
        cmbMonth.addItem(String.valueOf(i));
    }

    // Years
    for (int i = 1950; i <= 2026; i++) {
        cmbYear.addItem(String.valueOf(i));
    }
}
    private void cargarDatosUsuario() {

    User user = session.getCurrentUser();

    if (user == null) {
        return;
    }

    txtFirstName.setText(user.getFirstName());
    txtLastName.setText(user.getLastName());
    txtEmailOrPhone.setText(user.getEmailOrPhone());

    if (user.getBirthDate() != null) {

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(user.getBirthDate());

        cmbDay.setSelectedItem(String.valueOf(calendar.get(Calendar.DAY_OF_MONTH)));
        cmbMonth.setSelectedItem(String.valueOf(calendar.get(Calendar.MONTH) + 1));
        cmbYear.setSelectedItem(String.valueOf(calendar.get(Calendar.YEAR)));
    }
}
    

   public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(() -> {
        new Profile().setVisible(true);
    });

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        systemBtn = new javax.swing.JButton();
        plantBtn = new javax.swing.JButton();
        loteBtn = new javax.swing.JButton();
        monitoreoBtn = new javax.swing.JButton();
        solutionBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        informationLbl = new javax.swing.JLabel();
        informationPanel = new javax.swing.JPanel();
        nameLbl = new javax.swing.JLabel();
        lastNameLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmailOrPhone = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        birthdayLbl = new javax.swing.JLabel();
        cmbDay = new javax.swing.JComboBox<>();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        changePasswordLbl = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        newLbl = new javax.swing.JLabel();
        checkPassLbl = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JTextField();
        btnChangePassword = new javax.swing.JButton();
        txtNewPassword = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmailOrPhone = new javax.swing.JLabel();
        lblBirthDate = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        LabelIcon = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        principalPanel.setBackground(new java.awt.Color(233, 225, 225));
        principalPanel.setPreferredSize(new java.awt.Dimension(791, 550));

        menuPanel.setBackground(new java.awt.Color(11, 94, 32));
        menuPanel.setPreferredSize(new java.awt.Dimension(180, 305));

        homeBtn.setText("Inicio");
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setFocusPainted(false);

        systemBtn.setText("Sistema Huerto");
        systemBtn.setBorderPainted(false);
        systemBtn.setContentAreaFilled(false);
        systemBtn.setFocusPainted(false);

        plantBtn.setText("Plantas");
        plantBtn.setBorderPainted(false);
        plantBtn.setContentAreaFilled(false);
        plantBtn.setFocusPainted(false);

        loteBtn.setText("Lotes");
        loteBtn.setBorderPainted(false);
        loteBtn.setContentAreaFilled(false);
        loteBtn.setFocusPainted(false);

        monitoreoBtn.setText("Monitoreo");
        monitoreoBtn.setBorderPainted(false);
        monitoreoBtn.setContentAreaFilled(false);
        monitoreoBtn.setFocusPainted(false);

        solutionBtn.setText("Solució Nutritiva");
        solutionBtn.setBorderPainted(false);
        solutionBtn.setContentAreaFilled(false);
        solutionBtn.setFocusPainted(false);

        profileBtn.setBackground(new java.awt.Color(66, 127, 53));
        profileBtn.setText("Mi Perfil");
        profileBtn.setBorderPainted(false);
        profileBtn.setFocusPainted(false);

        logoutBtn.setText("Cerrar Sesión");
        logoutBtn.setBorderPainted(false);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setFocusPainted(false);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(systemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plantBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(monitoreoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(solutionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(homeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(systemBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plantBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monitoreoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solutionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        informationLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        informationLbl.setForeground(new java.awt.Color(58, 90, 64));
        informationLbl.setText("Información Personal");

        informationPanel.setBackground(new java.awt.Color(255, 255, 255));

        nameLbl.setForeground(new java.awt.Color(58, 90, 64));
        nameLbl.setText("Nombre");

        lastNameLbl.setForeground(new java.awt.Color(58, 90, 64));
        lastNameLbl.setText("Apellido");

        phoneLbl.setForeground(new java.awt.Color(58, 90, 64));
        phoneLbl.setText("Correo / Telefono");

        txtFirstName.setBackground(new java.awt.Color(204, 204, 204));
        txtFirstName.setForeground(new java.awt.Color(51, 51, 51));
        txtFirstName.setText("Nombre");

        txtLastName.setBackground(new java.awt.Color(204, 204, 204));
        txtLastName.setForeground(new java.awt.Color(51, 51, 51));
        txtLastName.setText("Apellido paterno");

        txtEmailOrPhone.setBackground(new java.awt.Color(204, 204, 204));
        txtEmailOrPhone.setForeground(new java.awt.Color(51, 51, 51));
        txtEmailOrPhone.setText("Correo o teléfono");

        btnUpdate.setBackground(new java.awt.Color(21, 101, 192));
        btnUpdate.setText("Modificar");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setBackground(new java.awt.Color(211, 47, 47));
        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        birthdayLbl.setForeground(new java.awt.Color(58, 90, 64));
        birthdayLbl.setText("Fecha de Nacimiento");

        cmbDay.setBackground(new java.awt.Color(204, 204, 204));
        cmbDay.setForeground(new java.awt.Color(51, 51, 51));
        cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbMonth.setBackground(new java.awt.Color(204, 204, 204));
        cmbMonth.setForeground(new java.awt.Color(51, 51, 51));
        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbYear.setBackground(new java.awt.Color(204, 204, 204));
        cmbYear.setForeground(new java.awt.Color(51, 51, 51));
        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout informationPanelLayout = new javax.swing.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addComponent(birthdayLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informationPanelLayout.createSequentialGroup()
                        .addComponent(phoneLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailOrPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(informationPanelLayout.createSequentialGroup()
                            .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, informationPanelLayout.createSequentialGroup()
                            .addComponent(lastNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastNameLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLbl)
                    .addComponent(txtEmailOrPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthdayLbl)
                    .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18))
        );

        changePasswordLbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        changePasswordLbl.setForeground(new java.awt.Color(58, 90, 64));
        changePasswordLbl.setText("Cambiar Contraseña");

        passwordPanel.setBackground(new java.awt.Color(255, 255, 255));

        newLbl.setForeground(new java.awt.Color(58, 90, 64));
        newLbl.setText("Nueva Contraseña");

        checkPassLbl.setForeground(new java.awt.Color(58, 90, 64));
        checkPassLbl.setText("Verificar Contraseña");

        txtConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtConfirmPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtConfirmPassword.setText("Verefica la nueva contraseña");

        btnChangePassword.setBackground(new java.awt.Color(21, 101, 192));
        btnChangePassword.setText("Cambiar");
        btnChangePassword.addActionListener(this::btnChangePasswordActionPerformed);

        txtNewPassword.setBackground(new java.awt.Color(204, 204, 204));
        txtNewPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtNewPassword.setText("Nueva contraseña");

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(passwordPanelLayout.createSequentialGroup()
                        .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkPassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNewPassword)
                            .addComponent(txtConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newLbl)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkPassLbl)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnChangePassword)
                .addGap(28, 28, 28))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstName.setForeground(new java.awt.Color(58, 90, 64));
        lblFirstName.setText("Nombre");

        lblLastName.setForeground(new java.awt.Color(58, 90, 64));
        lblLastName.setText("Apellido");

        lblEmailOrPhone.setForeground(new java.awt.Color(58, 90, 64));
        lblEmailOrPhone.setText("Correo/Teléfono");

        lblBirthDate.setForeground(new java.awt.Color(58, 90, 64));
        lblBirthDate.setText("Fecha de Nacimiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblEmailOrPhone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(134, Short.MAX_VALUE)
                        .addComponent(lblBirthDate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLastName)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(lblLastName))
                .addGap(18, 18, 18)
                .addComponent(lblEmailOrPhone)
                .addGap(18, 18, 18)
                .addComponent(lblBirthDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        LabelIcon.setText("jLabel1");

        btnMenu.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        btnMenu.setText("☰");
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(this::btnMenuActionPerformed);

        titleLbl.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        titleLbl.setText("Mi Perfil");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu)
                .addGap(138, 138, 138)
                .addComponent(LabelIcon)
                .addGap(188, 188, 188)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenu)
                    .addComponent(LabelIcon)
                    .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(changePasswordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, principalPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(principalPanelLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(informationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(principalPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 41, Short.MAX_VALUE))))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addComponent(informationLbl)
                        .addGap(4, 4, 4)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(changePasswordLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        getContentPane().add(principalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        animarMenu();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        User user = session.getCurrentUser();
        if (user == null) {

    JOptionPane.showMessageDialog(
            this,
            "No hay una sesión activa.");

    return;
}

user.setFirstName(txtFirstName.getText().trim());
user.setLastName(txtLastName.getText().trim());
user.setEmailOrPhone(txtEmailOrPhone.getText().trim());

String birthDate = cmbYear.getSelectedItem() + "-"
        + cmbMonth.getSelectedItem() + "-"
        + cmbDay.getSelectedItem();

user.setBirthDate(java.sql.Date.valueOf(birthDate));

UserDAO userDAO = new UserDAO();

if (userDAO.updateUser(user)) {

    JOptionPane.showMessageDialog(
            this,
            "Datos actualizados correctamente.");

} else {

    JOptionPane.showMessageDialog(
            this,
            "No fue posible actualizar los datos.");
}
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        // TODO add your handling code here:
        String newPassword = txtNewPassword.getText().trim();
String confirmPassword = txtConfirmPassword.getText().trim();

if (newPassword.isEmpty() || confirmPassword.isEmpty()) {

    JOptionPane.showMessageDialog(
            this,
            "Completa ambos campos.");

    return;
}

if (!newPassword.equals(confirmPassword)) {

    JOptionPane.showMessageDialog(
            this,
            "Las contraseñas no coinciden.");

    return;
}

User user = session.getCurrentUser();
if(user == null) {

    JOptionPane.showMessageDialog(
            this,
            "No hay una sesión activa.");

    return;
}

UserDAO userDAO = new UserDAO();

if (userDAO.updatePassword(user.getUserId(), newPassword)) {

    user.setPassword(newPassword);

    JOptionPane.showMessageDialog(
            this,
            "Contraseña actualizada correctamente.");

    txtNewPassword.setText("");
    txtConfirmPassword.setText("");

} else {

    JOptionPane.showMessageDialog(
            this,
            "No fue posible actualizar la contraseña.");
}
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de eliminar tu cuenta?\nEsta acción no se puede deshacer.",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION);

if (option == JOptionPane.YES_OPTION) {

    User user = session.getCurrentUser();
    if (user == null) {

    JOptionPane.showMessageDialog(
            this,
            "No hay una sesión activa.");

    return;
}

    UserDAO userDAO = new UserDAO();

    if (userDAO.deleteUser(user.getUserId())) {

        session.logout();

        JOptionPane.showMessageDialog(
                this,
                "La cuenta fue eliminada correctamente.");

        new Login().setVisible(true);

        dispose();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "No fue posible eliminar la cuenta.");
    }
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelIcon;
    private javax.swing.JLabel birthdayLbl;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel changePasswordLbl;
    private javax.swing.JLabel checkPassLbl;
    private javax.swing.JComboBox<String> cmbDay;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel informationLbl;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JLabel lblBirthDate;
    private javax.swing.JLabel lblEmailOrPhone;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton loteBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton monitoreoBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel newLbl;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JButton plantBtn;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton solutionBtn;
    private javax.swing.JButton systemBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtEmailOrPhone;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNewPassword;
    // End of variables declaration//GEN-END:variables
}
